image: node:16

clone:
  depth: full

pipelines:
  custom:
    deployment-to-staging:
       - step:
          name: 'Build app'
          caches:
            - node
          script:
            - npm install --quiet
            - npm run build --progress=false
          artifacts:
            - dist/**
       - step:
           name: Create artifact
           script: 
             - git archive --format=tar.gz new_design_project -o application.tar.gz 
           artifacts: 
           - application.tar.gz
       - step:
           name: Deploy to heroku
           deployment: staging
           caches:
             - node
           script:
             - pipe: atlassian/heroku-deploy:1.1.4
               variables:
                 HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
                 HEROKU_APP_NAME: $HEROKU_STAGING_APP_NAME
                 ZIP_FILE: "application.tar.gz"
                 WAIT: 'true'
    deployment-to-prod:
       - step:
          name: 'Build app'
          caches:
            - node
          script:
            - npm install --quiet
            - npm run build --progress=false
          artifacts:
            - dist/**
       - step:
           name: Create artifact
           script: 
             - git archive --format=tar.gz new_design_project -o application.tar.gz 
           artifacts: 
           - application.tar.gz
       - step:
           name: Deploy to heroku
           deployment: staging
           caches:
             - node
           script:
             - pipe: atlassian/heroku-deploy:1.1.4
               variables:
                 HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
                 HEROKU_APP_NAME: $HEROKU_PRODUCTION_APP_NAME
                 ZIP_FILE: "application.tar.gz"
                 WAIT: 'true'